### ISSUE TITLE
пофіксити zoom на робочій карті

### ISSUE THREAD

**Issue by rommelnyk** [digiU-DigitalPolice/digitalpolice-web#1]
[http://162.211.230.155:8000/app/#/map](url)  - на цій карті, яка є нашою основою із розробки сервісу для поліції і громадян, поки що не можна приблизити карту ближче ніж до масштабу всього міста в межах екрана. 
Потрібно виправити це і дати можливість користувачу наближатися настільки близько, наскільки дозволяє leaflet і openstreetmap - до рівнів вулиць і окремих будинків. 
Ось як це в наших конкурентів - 
![zoom level](https://cloud.githubusercontent.com/assets/4158059/15823601/13b05682-2c04-11e6-8b6b-745a51b7a18d.jpg)

**Comment by diadeep** [comment]
а мені нащо кинув?

Пн, 6 июня 2016 г. в 17:10, rommelnyk notifications@github.com:

**Comment by rommelnyk** [comment]
@diadeep тобі нічого не кидав. це нове issue для виконання :)

**Comment by vitaliikravets** [comment]
Перевірив, зум пофіксано. @LynxUA, gut gemacht!

**Comment by vitaliikravets** [comment]
Щоб issue закривалося само по собі, в коментарі коміту можна вказати щось на зразок "Fixed #1" або "Closes #1". І тоді issue закриється автоматично.
