### ISSUE TITLE
Додати кластеризацію на клієнті

### ISSUE THREAD

**Issue by vitaliikravets** [digiU-DigitalPolice/digitalpolice-web#24]
**Як користувач** сайту Цифрова Поліція,
**я хочу** бачити маркери на мапі погрупованими,
**для того**, щоб краще та швидше читати мапу.

Критерії прийняття:
- [x] маркери групуються у кластери
- [x] кластери показують кількість погрупованих маркерів
- [x] кластери розпадаються на меньші кластери/маркери при зумі
- [x] кластери розпадаються на меньші кластери/маркери при кліку по кластеру

**Comment by yashka713** [comment]
Які критерії прийняття issue?

**Comment by pubsy** [comment]
- маркери групуються у кластери
- кластери показують кількість погрупованих маркерів
- кластери розпадаються на меньші кластери/маркери при зумі
- кластери розпадаються на меньші кластери/маркери при кліку по кластеру
