### ISSUE TITLE
Відображення на Leaflet маркерів кластеризованих на сервері

### ISSUE THREAD

**Issue by vitaliikravets** [digiU-DigitalPolice/digitalpolice-web#4]
Leaflet має прості готові рішення для клієнтської кластеризації. Але нам не підходить цей підхід через обєм данних що мусять бути передані сервером на клієнт.
Ми плануємо кластеризувати маркері на сервері, а Leaflet лишається правильно ці кластери відобразити.
Критерії:
- [x] У запиті на сервер мусить бути присутнім значення приближення (zoom)
- [x] У запиті на сервер мусять бути присутніми координати крайніх ПдЗх та ПнСх точок на мапі, що відображається
- [x] При натисканні на маркер, має відбуватися зближення з одночасним центруванням обраного маркера

**Comment by vitaliikravets** [comment]
Одним з плагінів який можна використати:
https://github.com/Leaflet/Leaflet.markercluster

**Comment by rommelnyk** [comment]
кластери будуть показувати просто кількість злочинів. типи злочинів відображатимуться окремими піктограмками (надамо дизайн пізніше) при максимальному зумі. 
приклад ось тут:

![image](https://cloud.githubusercontent.com/assets/4158059/16518038/6e0be072-3f89-11e6-89fc-f6fff1a114d9.png)

а коли зумимо ближче, то кластери розпадаються на окремі маркери-злочини. і кожен маркер це 1 злочин: вбивство, крадіжка, тощо. 
Коли кластери - це просто сукупність будь-яких злочинів. Залежно відо того, що вибрав користувач. Користувач може вибрати всі злочини, може вибрати деілька, чи якийсь один. 
![image](https://cloud.githubusercontent.com/assets/4158059/16518087/aa69e08c-3f89-11e6-8956-4b0fd300f8c6.png)

**Comment by rommelnyk** [comment]
зразок простого кластерування - карта ремонту доріг України
http://mtu.gov.ua/intermap/#15
