### ISSUE TITLE
 Зміна приближення (zoom) має оновлювати груповані маркери на мапі

### ISSUE THREAD

**Issue by vitaliikravets** [digiU-DigitalPolice/digitalpolice-web#7]
**Як користувач** інтерактивної мапи злочинів, **я хочу**, щоб групування маркерів було меньш інтенсивним при наближенні та більш інтенсивним при віддалені, **для того**, щоб будь яке віддалення було максимально інформативним.

Для цього небхідно при зміні значення приближення у leaflet, робити запит на отримання групованих маркерів злочинів на сервер та оновлювати мапу відповідно до отриманої відповіді.

Acceptance criteria:
- [x] Натискання на кнопку + та - на мапі оновлює груповані маркери на мапі
- [x] Приближення за допомогою скролу мишки оновлює груповані маркери на мапі
- [x] Приближення на декількі рівнів одразу - оновлює мапу лише один раз (відправляє один запит)

**Comment by vitaliikravets** [comment]
Привіт @yashka713, глянь до опису. Це та issue, що ми обговорювали.

**Comment by yashka713** [comment]
@pubsy Для вирішення 3 пункту можна використати кастомний scrollWheelZoom. Тобто змінити його параметр wheelDebounceTime в самій бібліотеці Leaflet. Я спробував зробити його кастомізацію, як тут запропоновано:
[https://github.com/Leaflet/Leaflet/pull/2836/commits/f5cfddb60d174f1f8d098ca4257f84695e31e0c2](https://github.com/Leaflet/Leaflet/pull/2836/commits/f5cfddb60d174f1f8d098ca4257f84695e31e0c2) - досить непогано, але плавності в скролі - не вистачає.

**Comment by vitaliikravets** [comment]
@yashka713 А як з приближенням за допомогою кнопочок + - ?

**Comment by yashka713** [comment]
@pubsy нажаль, це стосується лише скролу.

**Comment by vitaliikravets** [comment]
У звязку з відмовою від серверної кластеризації - більше не актуально.
